#!/bin/bash

../pasmo_assembler/pasmo -v chronos_zxbeeper.asm chronos_zxbeeper.bin chronos_zxbeeper.sym &&
../pasmo_assembler/pasmo -v chronos_zxbeeper_ay.asm chronos_zxbeeper_ay.bin chronos_zxbeeper_ay.sym &&
python scripts/make_ini.py &&
wine ../aymaker/AYMakeR.exe chronos_zxbeeper.ini
